core:
  distance:
    desired: 0.3
    detection:
      trigger_base: 0.015
  buffer:
    movement:
      sec: 0
      nsec: 300000000
    detection:
      sec: 2
    search:
      sec: 4
    motion_detect:
      sec: 2
  velocity:
    linear:
      maximum: 0.22
      coefficient: 0.12
    rotational:
      maximum: 0.5
      coefficient: 2
      buffer_coefficient: 0.5
  frequency:
    interval:
      fiducial: 10
      detection: 10
    cmd_vel: 10
    search_preempt: 10
    motion_detect: 5
    motion_detect_linger: 0
  size:
    detection_deque: 10
  target_fiducials:
    warm:
    - 100
    - 101
    cold:

robot:
  camera:
    horizontal_fov: 62.2
    vertical_fov: 48.8
    pose:
      orientation:
        x:
          coefficient: -1
          adjustment: ~
        y:
          coefficient: -1
          adjustment: ~
        z:
          coefficient: -1
          adjustment: ~

tf:
  frame_name:
    world: map
    robot: base_footprint
    camera: base_camera
    target: target
